from __future__ import annotations

from typing import Any

from fastapi import APIRouter, BackgroundTasks, Request

from ...contracts.spaces import (
    EnterSpaceRequest,
    HomeMemberWriteRequest,
    PlaceRelationshipRequest,
    RelationshipDecisionRequest,
    SchoolEnrollmentRequest,
    SpaceCreateRequest,
    SpaceListResponse,
    SpaceUpdateRequest,
    VisitorNoteCreateRequest,
    VisitorNoteListResponse,
)
from .auth import CREATOR_CAPABILITY, require_session_capability
from .common import get_user_id, spaces_service

router = APIRouter(prefix="/spaces", tags=["spaces"])


@router.get("", response_model=SpaceListResponse)
def list_spaces(
    request: Request,
    lat: float | None = None,
    lon: float | None = None,
    radius: float = 5000,
    access: str | None = None,
    status: str | None = None,
    place_type: str = "",
    special_type: str = "",
    q: str = "",
    search: str = "",
    owner_id: str = "",
    limit: int | None = None,
    offset: int = 0,
) -> dict[str, Any]:
    query = q or search
    return spaces_service(request).list_spaces(
        lat=lat,
        lon=lon,
        radius=radius,
        access=access,
        status=status,
        place_type=place_type,
        special_type=special_type,
        query=query,
        owner_id=owner_id,
        limit=limit,
        offset=offset,
    )


@router.post("")
def create_space(request: Request, data: SpaceCreateRequest) -> dict[str, Any]:
    require_session_capability(request, CREATOR_CAPABILITY)
    return spaces_service(request).create_space(data.to_payload(), get_user_id(request))


@router.get("/{space_id}")
def get_space(request: Request, space_id: str, view: str = "") -> dict[str, Any]:
    return spaces_service(request).get_space(space_id, get_user_id(request), view=view)


@router.get("/{space_id}/share")
def get_space_share(request: Request, space_id: str) -> dict[str, Any]:
    """Return a share payload for the requested Space.

    Args:
        request: FastAPI request containing app state and user context.
        space_id: Space identifier to serialize for sharing.

    Returns:
        Share payload generated by the application service.

    Side effects:
        None; this route only reads Space metadata.
    """
    return spaces_service(request).get_tavern_share(
        space_id,
        get_user_id(request),
        str(request.base_url).rstrip("/"),
    )


@router.put("/{space_id}")
def update_space(request: Request, space_id: str, data: SpaceUpdateRequest) -> dict[str, Any]:
    require_session_capability(request, CREATOR_CAPABILITY)
    return spaces_service(request).update_space(space_id, data.to_payload(), get_user_id(request))


@router.delete("/{space_id}")
def delete_space(request: Request, space_id: str) -> dict[str, Any]:
    require_session_capability(request, CREATOR_CAPABILITY)
    return spaces_service(request).delete_space(space_id, get_user_id(request))


@router.post("/{space_id}/home-members")
def add_home_member(request: Request, space_id: str, data: HomeMemberWriteRequest) -> dict[str, Any]:
    require_session_capability(request, CREATOR_CAPABILITY)
    return spaces_service(request).add_home_member(space_id, data.to_payload(), get_user_id(request))


@router.get("/{space_id}/school-members")
def list_school_members(request: Request, space_id: str) -> dict[str, Any]:
    return spaces_service(request).list_school_members(space_id, get_user_id(request))


@router.post("/{space_id}/relationships/school-enrollments")
def create_school_enrollment(request: Request, space_id: str, data: SchoolEnrollmentRequest) -> dict[str, Any]:
    require_session_capability(request, CREATOR_CAPABILITY)
    return spaces_service(request).create_school_enrollment(space_id, data.to_payload(), get_user_id(request))


@router.post("/{space_id}/relationships")
def create_place_relationship(request: Request, space_id: str, data: PlaceRelationshipRequest) -> dict[str, Any]:
    require_session_capability(request, CREATOR_CAPABILITY)
    return spaces_service(request).create_place_relationship(space_id, data.to_payload(), get_user_id(request))


@router.put("/{space_id}/relationships/{relationship_id}")
def decide_place_relationship(
    request: Request,
    space_id: str,
    relationship_id: str,
    data: RelationshipDecisionRequest,
) -> dict[str, Any]:
    require_session_capability(request, CREATOR_CAPABILITY)
    return spaces_service(request).decide_place_relationship(
        space_id,
        relationship_id,
        data.to_payload(),
        get_user_id(request),
    )


@router.post("/{space_id}/enter")
def enter_space(
    request: Request,
    background_tasks: BackgroundTasks,
    space_id: str,
    data: EnterSpaceRequest | None = None,
) -> dict[str, Any]:
    user_id = get_user_id(request)
    result = spaces_service(request).enter_space(
        space_id,
        password=data.password if data else "",
        user_id=user_id,
        visitor_gender=data.visitor_gender if data else "",
    )

    # Trigger notification for tavern owner
    if user_id:
        tavern = spaces_service(request).store.get_space(space_id)
        if tavern and tavern.owner_id and tavern.owner_id != user_id:
            from ...core.notifications import notify_new_visitor
            background_tasks.add_task(
                notify_new_visitor,
                space_id,
                tavern.name,
                tavern.owner_id,
                user_id or "访客",
            )

    return result


@router.get("/{space_id}/metrics")
def get_space_metrics(request: Request, space_id: str) -> dict[str, Any]:
    """Return owner-visible metrics for the requested Space.

    Args:
        request: FastAPI request containing app state and user context.
        space_id: Space identifier to inspect.

    Returns:
        Aggregated Space metrics for the authorized owner.

    Side effects:
        None; this route only reads the configured store.
    """
    return spaces_service(request).get_tavern_metrics(
        space_id,
        user_id=get_user_id(request),
    )


# ─────────────────────────────────────────
# Owner-visible Visitor Notes
# ─────────────────────────────────────────

@router.get("/{space_id}/visitor-notes", response_model=VisitorNoteListResponse)
def list_visitor_notes(
    request: Request,
    space_id: str,
    limit: int = 20,
    offset: int = 0,
) -> dict[str, Any]:
    return spaces_service(request).list_visitor_notes(
        space_id,
        get_user_id(request),
        limit=limit,
        offset=offset,
    )


@router.post("/{space_id}/visitor-notes")
def create_visitor_note(
    request: Request,
    background_tasks: BackgroundTasks,
    space_id: str,
    data: VisitorNoteCreateRequest,
) -> dict[str, Any]:
    user_id = get_user_id(request)
    result = spaces_service(request).create_visitor_note(
        space_id,
        data.to_payload(),
        user_id,
    )

    # Trigger notification for tavern owner
    tavern = spaces_service(request).store.get_space(space_id)
    if tavern and tavern.owner_id and tavern.owner_id != user_id:
        from ...core.notifications import notify_new_guest_message
        background_tasks.add_task(
            notify_new_guest_message,
            space_id,
            tavern.name,
            tavern.owner_id,
            data.visitor_nickname or "访客",
        )

    return result


@router.delete("/{space_id}/visitor-notes/{note_id}")
def delete_visitor_note(
    request: Request,
    space_id: str,
    note_id: str,
) -> dict[str, Any]:
    service = spaces_service(request)
    user_id = get_user_id(request)
    note_store = service.visitor_note_store
    note = note_store.get_note(space_id, note_id) if note_store else None
    if note and note.get("visitor_id") != user_id:
        require_session_capability(request, CREATOR_CAPABILITY)
    return service.delete_visitor_note(
        space_id,
        note_id,
        user_id,
    )
