import type { RpgMap, RpgPlayer } from "@rpgjs/server";
import {
  MIRROR_TILE_SIZE,
  type TilePoint,
} from "../../world/terrain-contract.ts";

export const OUTDOOR_MAP_ID = "simplemap";
export const HOUSE_STAKE_ID = "HouseStake";
export const WELCOME_NPC_EVENT_ID = "welcome-npc";

/** Converts one reviewed tile coordinate to the RPGJS top-left pixel position. */
export function tileToPixel(tile: TilePoint): { x: number; y: number } {
  return { x: tile.x * MIRROR_TILE_SIZE, y: tile.y * MIRROR_TILE_SIZE };
}

/** Converts the player's top-left RPGJS pixel position to the occupied tile coordinate. */
export function playerTile(player: Pick<RpgPlayer, "x" | "y">): TilePoint {
  return {
    x: Math.floor(player.x() / MIRROR_TILE_SIZE),
    y: Math.floor(player.y() / MIRROR_TILE_SIZE),
  };
}

/** Reads a normalized public map ID from one RPGJS room without exposing its room prefix. */
export function runtimeMapId(map: RpgMap | null): string {
  const mapData = map?.data?.();
  return String(mapData?.id ?? (map as { id?: unknown } | null)?.id ?? "").replace(/^map-/, "");
}

/** Returns the stable owner-scoped runtime ID generated by RPGJS for the welcome scenario event. */
export function welcomeNpcRuntimeId(playerId: string): string {
  return `${WELCOME_NPC_EVENT_ID}::${playerId}`;
}
